# Generated by Django 6.0 on 2026-01-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_aircraft_id_alter_airport_id_alter_baggage_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='gate',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='status',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Bilet Fiyatı'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=10),
        ),
    ]
