# Generated by Django 6.0 on 2026-01-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_flight_price_flight_aircraft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taban Fiyat'),
        ),
    ]
