# Generated by Django 6.0 on 2026-01-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_flight_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='base_price',
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
